### ISSUE TITLE
chore: create basic helia-ipns example

### ISSUE THREAD

**Issue by TJKoury** [ipfs/helia-ipns#59]
Here's a [test sandbox](https://codesandbox.io/p/sandbox/helia-connectivity-demo-forked-hrr2yx?file=%2Fnode_modules%2F%40helia%2Funixfs%2Fdist%2Fsrc%2Findex.d.ts%3A1%2C1), using the same instance / transport as the helia instance that seems to be working on the page.

The error I get is "PublishError.InsufficientPeers", even though there are plenty of peers. 

_Originally posted by @TJKoury in https://github.com/ipfs/helia-ipns/issues/56#issuecomment-1613765497_

**Comment by BigLep** [comment]
Agreed that there should be a usage example showing how use helia-ipns.  We use to have this for js-ipfs in docs.ipfs.tech in https://github.com/ipfs/ipfs-docs/blob/8f1022a9d94b4c13e70ba17a4c976f4554394418/docs/how-to/publish-ipns.md#publishing-ipns-names-programmatically-with-js-ipfs

**Comment by TJKoury** [comment]
@BigLep Is the error I’m receiving a known issue (or am I just doing it wrong)?

**Comment by BigLep** [comment]
@TJKoury : I'll need one of the @ipfs/helia-dev maintainers to look.  This should get picked up during the next triage session.

**Comment by nhattan097** [comment]
I start helia on nextjs, using at api, and I have same issue too when I public CID

**Comment by achingbrain** [comment]
`PublishError.InsufficientPeers` is an error emitted by `@chainsafe/libp2p-gossipsub` when you try to publish a message on a topic that doesn't have any listeners.

It's thrown because the message will never leave your local node.

Your options are either:

a) Ensure there are peers subscribed to the given topic (not just network peers)
b) Disable the error by specifying `allowPublishToZeroPeers: true` when configuring gossipsub - https://github.com/ChainSafe/js-libp2p-gossipsub/blob/master/src/index.ts#L107-L108
c) Do not use the pubsub routing, only the DHT routing

**Comment by nhattan097** [comment]
Let me ask something: when I start Helia on FE, specific is Next.js, except `import {create} from "helia"` and `create()` it, what else do I need to run? And then, when I using helia-ipns to public CID and I got this error `PublishError.InsufficientPeers`. I start `create()` at route /api/ipfs.ts. Or am I just doing it wrong?

**Comment by SgtPooki** [comment]
@nhattan097 what are you trying to accomplish specifically?

The error `PublishError.InsufficientPeers` was clarified above in that it's erroring due to not having any peers to publish to. 

You can check out https://github.com/libp2p/js-libp2p-examples/tree/main/examples/js-libp2p-example-browser-pubsub for an example on using libp2p's pubsub mechanism. 

Basically, to make sure there are peers listening, you can call `helia.libp2p.services.pubsub.getSubscribers(topic)` which you can see in that example at https://github.com/libp2p/js-libp2p-examples/blob/e5396ce1a109c368bc6b1c6be3a6ba8640dc9777/examples/js-libp2p-example-browser-pubsub/index.js#L142-L153

Leaving this open to track creating a helia-ipns example

**Comment by achingbrain** [comment]
Closing due to staleness - please open a new issue if this is still a problem.
